Simple mvvm application#1
LarionovKirill/MVVM_Learning pull request #1
Opened 2023-09-27 14:25 UTC by LarionovKirill

2023-10-02 06:47 UTC, Ershovoy requested changes

2023-10-02 06:47 UTC, Ershovoy commented on Contacts/Contacts/ViewModel/MainVM.cs
> +                            int a = 0;
?

2023-10-02 06:47 UTC, Ershovoy commented on Contacts/Contacts/ViewModel/MainVM.cs
> +                            ContactSerializer.SaveContact(Contact);
Валидация должна производиться в Model

2023-10-03 14:16 UTC, LarionovKirill commented on Contacts/Contacts/ViewModel/MainVM.cs
> +                            int a = 0;
Согласен, тупанул, нужно было просто catch чтоб не пустой был.

2023-10-03 14:16 UTC, LarionovKirill commented on Contacts/Contacts/ViewModel/MainVM.cs
> +                            ContactSerializer.SaveContact(Contact);
Это я понимал и изначально так и сделал, но если оно так и будет, то вылетит exception раньше нужного, потому что валидация будет происходить на каждое изменение. Я хотел выдавать сообщение, но потом понял, что лучше подсвечивать textbox как раньше, поэтому и спрашивал у тебя как сделать, потому что сейчас вообще ничего непонятно с этим WPF

2023-10-04 05:35 UTC, merged